apiVersion: v1
kind: Service
metadata:
  name: bulldozer-service
spec:
  type: LoadBalancer
  selector:
    app: bulldozer-app
  ports:
    - protocol: TCP
      port: 80        # External port users will access
      targetPort: 8501  # Port your Streamlit app runs on inside container
